# Site settings
title: "Usama Hamid"
description: "Usama Hamid - Info"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Usama Hamid"
resume_title:                   "Senior Engineer"
resume_contact_email:           "usamahamid007@gmail.com"
resume_contact_telephone:       "+91 94880 46537"
resume_contact_address:         "Coimbatore, India"
resume_header_contact_info: "Coimbatore, India | +91 94880 46537 | usamahamid007@gmail.com"
resume_header_intro: "<p>Competent professional with <b>4.3+</b> year of experience in <b>Mobile and Web application development</b>, capable of adapting and striving to complete any challenge <br/> Proficient in Mobile app development in Android and associated data modeling based on MVC and MVP architecture <br/> Experienced veteran in every aspect of SDLC from Architecture design to Dev Ops <br/> Experienced in Web application development with <b>Spring, Spring Boot and Django framework</b></p>"

resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/usamahamid"
  resume_linkedin_url:          "https://www.linkedin.com/in/usama-hamid-73503494/"
  resume_website_url:           "https://usamahamid.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
